language: php
php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - sudo apt-get install colordiff
  - cd cloned
  - git clone https://github.com/zordius/lightncandy
  - cd ..
script:
  - php bin/hbreport F 32 T
